# -*- coding: utf-8 -*-
"""cie1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKp9Hh6FIBOZ6vz6QwszruxQy7l4DIz-
"""

import pandas as pd
Series_A=pd.Series([1,2,3,4,5])
Series_B=pd.Series([2,4,6,8,10])
common_item=Series_A[Series_A.isin(Series_B)]
print(common_item)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
data=pd.read_csv('/content/mtcars.csv')
data.head()

plt.figure(figsize=[8,8])
plt.hist(data['mpg'],edgecolor='k')
plt.title('frequency distrubution')
plt.xlabel('frequency')
plt.ylabel('mpg')
plt.show()

plt.figure(figsize=[6,6])
plt.scatter(data['mpg'],data['wt'],marker='*')
plt.title('relation between weight of the car and mpg')
plt.xlabel('car')
plt.ylabel('mpg')
plt.show()

trans=data['am'].value_counts()
plt.figure(figsize=[7,7])
trans.plot(kind='bar',color='blue')
plt.title('frequency disribution type of cars')
plt.xlabel('transmission type')
plt.ylabel('frequency')
plt.show()

plt.figure(figsize=[7,6])
plt.boxplot(data['mpg'],vert=True,notch=False,patch_artist=True)
plt.show()